name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Hatch
        run: pip install --upgrade hatch
      - name: Install dependencies
        run: hatch env create
      - name: Format
        run: hatch run format
      - name: Lint
        run: hatch run lint
      - name: Type check
        run: hatch run typecheck
      - name: Test
        run: hatch run test

