name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Hatch
        run: pip install --upgrade hatch
      - name: Install dependencies
        run: hatch env create
      - name: Lint
        run: hatch run lint
      - name: Type check
        run: hatch run typecheck
      - name: Test
        run: hatch run test

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Hatch
        run: pip install --upgrade hatch
      - name: Build package
        run: hatch build
      - name: Publish to PyPI
        env:
          HATCH_INDEX_USER: ${{ secrets.PYPI_USERNAME }}
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}
        run: hatch publish
